### PR TITLE
add dependabot

### PR DESCRIPTION
**Pull request by wesk**
*Issue #, if available:*

*Description of changes:*

Add dependabot to keep dependencies up-to-date

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ConnorBaker** [comment]
I'd recommend that you also add an entry for GitHub actions:

```yaml
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
```

It helps to keep on top of newer versions of different actions. For example, you're using v2 of `actions/checkout` while v3 is available: <https://github.com/actions/checkout/releases/tag/v3.2.0>. And for `actions/setup-python`, you're using v2 while v4 is available: <https://github.com/actions/setup-python/releases/tag/v4.3.1>. I'm not sure what policy you follow with respect to updates/approvals though!

Also, strings in YAML don't need to be quoted unless they start with or contain funky characters (unless that's your preference!). I don't know if there's a style guide you're following, but if there is, let me know!

**Comment by mseeger** [comment]
Just wondering what this is doing, and what one of us has to do as a reaction.

**Comment by mseeger** [comment]
Hello @wesk . What is the status on this PR? Is this ongoing, or should it be closed in favor of more recent developments?

**Comment by wesk** [comment]
@mseeger agreed. The integ tests will help ensure that these changes are safe to merge in an automated way, working on those now.

**Comment by wesk** [comment]
@ConnorBaker regarding: 
> Also, strings in YAML don't need to be quoted unless they start with or contain funky characters (unless that's your preference!). I don't know if there's a style guide you're following, but if there is, let me know!

I was following what GitHub shows in their docs, but you're right that it doesn't strictly need to be that way

**Comment by wesk** [comment]
It will start raising PRs like this one, which we can choose to merge or close: https://github.com/awslabs/Renate/pull/99

If we find that it is too noisy, we can turn it off or see if we can change the settings.

**Pull request merged**
