### PR TITLE
BB hashing fix

### PR DESCRIPTION
**Pull request by aaronkl**
*Description of changes:*

Computes a logical hash for parquet files to avoid differences between machines

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by geoalgo** [comment]
Cool, thanks for the quick fix!

**Review by wistuba — CHANGES_REQUESTED** [review]
doesn't work. I've tried `icml-xgboost` and it keeps regenerating. my hash: `25286c38b3e5a8286a1469613a875cce7d67e527ce48d85d83750ced78fcb0bf`

**Comment by mseeger** [comment]
This is a really difficult task, because Aaron himself cannot test it. I suggest Aaron and Martin work closely together for a bit, until this works out for Martin, which is probably sufficient for the others as well.

**Comment by aaronkl** [comment]
The problem seems to be different a precision of the pandas dataframes

**Review by wistuba — APPROVED** [review]
it works for me now.

**Pull request merged**
