### PR TITLE
Refactor transformer_wikitext2 benchmark (e.g., checkpointing)

### PR DESCRIPTION
**Pull request by mseeger**
*Issue #, if available:*

*Description of changes:*
Cleans up benchmark code, using lstm_wikitext2 as blueprint. In particular, the checkpointing is simplified, and unused args are removed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mseeger** [comment]
@aaronkl The default for `ffn_ratio` is 1. Is this correct? I thought it was 2 (at least in BERT).

**Comment by aaronkl** [comment]
Defaults are from the original implementationl

**Review by aaronkl — APPROVED** [review]
LGTM. Is there a reason why you merged the transformer code all into one file?

**Comment by mseeger** [comment]
I used to run into trouble when working with a venv where torch was not installed. Also, we do not use relative imports elsewhere. In the end, I just tried to make it look like lstm_wikitext2, because we know this works in all circumstances (SageMaker backend, checkpointing, ...).

**Pull request merged**
